spark:
  datasource: "data"
  init_src: "init"
  update_src: "update"
  target: "delta"
  update_query_columns: ["SIERT", "SIREN", "datederniertraitementetablissement"]
  read_format: "csv"
  read_options: 
    "delimiter": ";"
    "encoding": "UTF-8"
    "header": True
  spark_config: 
    "spark.jars.packages": "io.delta:delta-core_2.12:2.2.0"
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog"

delta:
  datasource: "data"
  source: "init" 
  target: "delta"
  update_query_columns: ["SIRET", "SIREN"] #to be confirmed if they are primary keys

api:
  api_url: "https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/economicref-france-sirene-v3/exports"
  format: "csv"
  update_params : "datederniertraitementetablissement"